### ISSUE TITLE
似乎没有翻译功能

### ISSUE THREAD

**Issue by cmd1152** [GoogolOwO/googol-translation#7]
我查看了源代码，他只替换了am和are变成is，并没有什么翻译功能，你可以试试google的翻译接口

**Comment by GoogolOwO** [comment]
THIS IS A BOT MESSAGE, IT NOT FOR ANY POINT FOR AUTHOR's MEAN. THIS MESSAGE CONTROLLING BY GITHUB ACTIONS.

----

Hi! This repository using Googolish, please check your issue using Chinglish:

- Change you are to you is
- Change I am to I is 
- Use language as simply as possible.

If you don't follow it, the problem possible can't solve it.

**Comment by GoogolOwO** [comment]
Yes, I know! But I can't be do it. Google translation have been GFWed in China.

This only can translation from English to Chinglish.

**Comment by GoogolOwO** [comment]
THIS IS A BOT MESSAGE, IT NOT FOR ANY POINT FOR AUTHOR's MEAN. THIS MESSAGE CONTROLLING BY GITHUB ACTIONS.

----

Hi! This repository using Googolish, please check your issue using Chinglish:

- Change you are to you is
- Change I am to I is 
- Use language as simply as possible.

If you don't follow it, the problem possible can't solve it.

**Comment by cmd1152** [comment]
> Yes, I know! But I can't be do it. Google translation have been GFWed in China.
> 
> This only can translation from English to Chinglish.

实际上，现在有google.hk这个东西

**Comment by cmd1152** [comment]
对了，我在这里回复下你在 https://note.freeflarum.com/d/161733-reset_chan%E4%BD%A0%E8%BF%9D%E6%B3%95%E4%BA%86 说的内容

> 第二百八十六条　【破坏计算机信息系统罪】违反国家规定，对计算机信息系统功能进行删除、修改、增加、干扰，造成计算机信息系统不能正常运行，后果严重的，处五年以下有期徒刑或者拘役；后果特别严重的，处五年以上有期徒刑。

这个指的是要入侵了你的电脑，然后修改你的程序才是，您可以通过gpt了解法律后再发言，谢谢！

**Comment by GoogolOwO** [comment]
@cmd1152 请勿发布离题 issue，这是违反 GitHub 规则的。如果你需要讨论那个内容，请前往那个论坛。

**Comment by cmd1152** [comment]
> @cmd1152 请勿发布离题 issue，这是违反 GitHub 规则的。

好的，感谢您的提醒，您可以使用国内的google通道来访问到google翻译

**Comment by GoogolOwO** [comment]
https://translate.google.cn and https://translate.google.com.cn is all unusable in China.

**Comment by GoogolOwO** [comment]
Won't fix

**Comment by GoogolOwO** [comment]
THIS IS A BOT MESSAGE, IT NOT FOR ANY POINT FOR AUTHOR's MEAN. THIS MESSAGE CONTROLLING BY GITHUB ACTIONS.

----

Hi! This repository using Googolish, please check your issue using Chinglish:

- Change you are to you is
- Change I am to I is 
- Use language as simply as possible.

If you don't follow it, the problem possible can't solve it.

**Comment by cmd1152** [comment]
> https://translate.google.cn and https://translate.google.com.cn is all unusable in China.

事实上，不是这些域名，我记得有个 hk 结尾的是可以使用的，我曾经就用他实现了中国境内的google翻译

**Comment by GoogolOwO** [comment]
.hk now unsuable
________________________________
发件人: cmd1152 ***@***.***>
发送时间: 2024年7月3日 11:17
收件人: GoogolOwO/googol-translation ***@***.***>
抄送: Googol ***@***.***>; State change ***@***.***>
主题: Re: [GoogolOwO/googol-translation] 似乎没有翻译功能 (Issue #7)


https://translate.google.cn and https://translate.google.com.cn is all unusable in China.

事实上，不是这些域名，我记得有个 hk 结尾的是可以使用的，我曾经就用他实现了中国境内的google翻译

―

**Comment by cmd1152** [comment]
>.hk now unsuavle

try https://google.com.hk ，我这边是可以访问的
